# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VKApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'Alamofire', '~> 5.3'
pod 'SwiftyJSON', '~> 4.0'
pod 'SwiftLint'
pod 'RealmSwift'

  # Pods for VKApp

  target 'VKAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'VKAppUITests' do
    # Pods for testing
  end

end
